### PR TITLE
sdk: update contracts version to v0.37.1

### PR DESCRIPTION
**Pull request by weilbith**
Part of #1951

### CODE REVIEW

**Comment by weilbith** [comment]
I assigned Talel as a reviewer specifically for the documentation. We are a small team and I had some issues with the existing documentation. Some things were out-of-date I needed to update, other were just not too good written. Since Talel hasn't read these docs so far, I would love to see if he can now follow them easily or if we need to improve them even more.

**Comment by weilbith** [comment]
PS: The integration tests are now updated as well.

**Comment by weilbith** [comment]
> To me, the docs are short and straight forward. I would have to try it out to see if I bump into any question marks but for now no objections from my side.

Could you maybe invest the half hour, take the master and attempt to update the light client to be compliant with Python client `v1.1.1`? If it is too much work don't worry and just stop. Just imagine next time you have to do it. :stuck_out_tongue:

**Comment by taleldayekh** [comment]
> take the master and attempt to update the light client to be compliant with Python client

Sure, I thought it was already done or do you mean just try it without actually merging the changes?

**Comment by weilbith** [comment]
@andrevmatos could you give it some final love and check the version numbers I used? Should be fast to verify. :upside_down_face: 
I would open the patch bump version PR afterwards.

**Comment by weilbith** [comment]
Thanks for the reviews. I just converted the draft PR to an actual one. I'll now clean up the fixup commits and merge this.

**Pull request merged**
