### PR TITLE
Bugfix/dapp build process warnings

### LINKED ISSUE #2854: dApp - build process reports infinite amount of warning output
## Description

This issue is caused by the combination of the Vuetify and Sass version. See the following issues for details: 
- vuetifyjs/vuetify#13694
- vuetifyjs/vuetify#13737
- [Vuetify v2.5.3 release notes](https://github.com/vuetifyjs/vuetify/releases/tag/v2.5.3)

Furthermore the `mini-css-extract-plugin` is causing warnings as well. We can safely ignore them as we use modules with Vue and therefore the conflicting loading order doesn't matter. See for details:

- vuejs/vue-cli#3771
- webpack-contrib/mini-css-extract-plugin#250
- facebook/create-react-app#5372

## Acceptance criteria
- No such verbose output of warnings

## Tasks
- [ ] downgrade Sass to `v1.32`
- [ ] ignore css-mini-... specific warnings

### PR DESCRIPTION
**Pull request by weilbith**
Fixes #2854

**Short description**
Just see the commit messages. Finally silence...

**Definition of Done**

- [x] Steps to manually test the change have been documented
- [x] Acceptance criteria are met
- [ ] Change has been manually tested by the reviewer (dApp) 

**Steps to manually test the change (dApp)**

1. Make sure to run `yarn install --force --frozen-lockfile`
2. Run `yarn workspace raiden-dapp build` and verify its just the minimal output without warnings

### CODE REVIEW

**Comment by weilbith** [comment]
No CHANGELOG entry necessary for this.

**Comment by weilbith** [comment]
The license checker was failing for an invalid version format of the Sass package.
... while writing this comment, it fails again. I'm confused.

**Comment by weilbith** [comment]
I tested it locally. Should work now.

**Review by agatsoh — APPROVED** [review]
LGTM

**Comment by weilbith** [comment]
I'll fix the conflicting files now.

**Comment by weilbith** [comment]
For some reason I fu**** up the dependencies with `master`. And also I have the next merge conflict due to a recent PR merge. I fix it...

**Pull request merged**
