### PR TITLE
WIP: This is only meant for testing in a draft PR!

### PR DESCRIPTION
**Pull request by weilbith**
Related to: #1773

@christianbrb please give this PR a try and do a comparison of how much this version uses your GPU. Simply go to a token and mint some of them. Or open the QR reader. I would suggest to do exactly the same for the deployed version at lightclient.trustlines.network and do a comparison.
For my PC without a dedicated GPU I get the same CPU usage (roughly +20%).

### CODE REVIEW

**Comment by weilbith** [comment]
This seem to be a more general problems as there are already issues on Vuetify. But apparently this kinda related to hardware and OS.
Could you maybe try [this](https://codepen.io/arthur_zhu/pen/gXOKVj?editors=1111)?

**Comment by christianbrb** [comment]
> Could you maybe try [this](https://codepen.io/arthur_zhu/pen/gXOKVj?editors=1111)?

Works fine for me :)

**Comment by weilbith** [comment]
Okay so just to be sure I understand your comment correctly:
You opened the link to the CodePen page I send you. Because of the circular progress component your PC was going crazy. Then you changed it to the linear progress component and your PC was calming down then. Correct?

**Comment by christianbrb** [comment]
@weilbith I have just clicked on the link and didn't change something. My computer stayed silent.

`v-progress-linear` also works fine.

My screen resolution is `1920x1080@59Hz `

**Comment by weilbith** [comment]
Okay, that is bad. At least from the perspective to solve this issue at our page. 
So could you do me the favor and try the original size. Just copy paste this as replacement for the left JS code. Except the surrounding components this is a copy from our code-base.

```js
<div id="app">
  <v-app id="inspire">
    <div>
      <v-progress-circular
          color="primary"
          :size="110"
          :width="7"
          indeterminate
       />
    </div>
  </v-app>
</div>
```

**Comment by weilbith** [comment]
Okay this is cumbersome and not promising. I go for a custom spinner. The code base should anyways use a shared component (actually parts of the code so already). This looks 95% the same and consumes nearly nothing. Just did a preview for Talel and he likes it.

**Comment by christianbrb** [comment]
> 
> 
> Okay this is cumbersome and not promising. I go for a custom spinner. The code base should anyways use a shared component (actually parts of the code so already). This looks 95% the same and consumes nearly nothing. Just did a preview for Talel and he likes it.

Ok, make sense.

**Comment by christianbrb** [comment]
> 
> 
> Okay, that is bad. At least from the perspective to solve this issue at our page.
> So could you do me the favor and try the original size. Just copy paste this as replacement for the left JS code. Except the surrounding components this is a copy from our code-base.
> 
> ```js
> <div id="app">
>   <v-app id="inspire">
>     <div>
>       <v-progress-circular
>           color="primary"
>           :size="110"
>           :width="7"
>           indeterminate
>        />
>     </div>
>   </v-app>
> </div>
> ```

This worked fine for me.

**Comment by weilbith** [comment]
Checkout the final solution at #1821

**Pull request closed without merging**
