### PR TITLE
3.0.0 -> 3.1.0

### PR DESCRIPTION
**Pull request by karlb**
# :cat: New Raiden Light Client SDK, dApp and CLI

> **INFO:** The Light Client SDK, CLI and dApp are all **work in progress** projects. All three projects have been released for **mainnet** and all code is available in the Light Client repository. As this release still has its limitations and is a **beta** release, it is crucial to read this readme including the security notes carefully before using the software.

This release brings the WebUI which was formerly only available for the Python Client to the Light Client. The previous UI is still available as usual. Use `--web-ui` with the CLI to bring up the WebUI.

Raiden SDK
-------------------------------
### Fixed
- [#3118] Dynamically set `config.revealTimeout` to half of `tokenNetworkRegistryContract.settleTimeout`, if it'd be smaller than default of 600s

### Changed
- [#3122] `Raiden.dumpDatabase` now returns an `AsyncIterable` of database rows objects, which allow to stream even big state dumps without having to accumulate everything in memory; also, it doesn't require stopping SDK to dump state anymore

### Added
- [#3123] `Raiden.getTransfers` method, an easier way to get, filter and paginate over past transfers.

[#3118]: https://github.com/raiden-network/light-client/pull/3118
[#3122]: https://github.com/raiden-network/light-client/issues/3122
[#3123]: https://github.com/raiden-network/light-client/issues/3123

Raiden dApp
-------------------------------
### Changed
- [#3122] `Backup State` doesn't require SDK to be shut down anymore

[#3122]: https://github.com/raiden-network/light-client/issues/3122

Raiden CLI
-------------------------------
### Added
- [#3122] `/api/v1/state.json` endpoint to allow downloading/backing up and `--load-state <path.json>` parameter to upload/rehydrate state/database in a fresh instance
- [#3123] **Experimental**: `--web-ui` option to serve [Raiden WebUI](https://github.com/raiden-network/webui) from `/ui` route; requires `yarn build:webui`

[#3122]: https://github.com/raiden-network/light-client/issues/3122
[#3123]: https://github.com/raiden-network/light-client/issues/3123

### CODE REVIEW

**Review by andrevmatos — CHANGES_REQUESTED** [review]
You need to bump the versions in the CHANGELOG files (and URLs at the bottom)

**Review by andrevmatos — APPROVED** [review]
lgtm, ty =)

**Comment by karlb** [comment]
> You need to bump the versions in the CHANGELOG files (and URLs at the bottom)

You're right. We did the changes, but did not `git add` them. Should be better, now.

**Comment by karlb** [comment]
The CLA assistant does give me a link to sign the CLA.

**Comment by andrevmatos** [comment]
It shouldn't block, we can force-merge. You can go ahead with the release =)

**Pull request merged**
