### PR TITLE
Service to download and serve a PR artifact

### LINKED ISSUE #1746: Build dApp in development mode on PRs
## Description
As part of #1511 , after #1745 the build files are exported as an artifact, but the build itself is done on `--mode ghpages`, which is production-optimized. I'd be nice to have the `build_dapp` step take into account the kind of CI run, and build for `development` in PRs, and `ghpages` (production) only on `master`/`tag` builds (the ones that run after the PR is merged/tagged).
Additionally, it'd be good if the file was compressed on `tar.gz`, as it'd more widely available than `.xz` (e.g. on alpine docker images), and the size difference is not that relevant here.

## Acceptance criteria
- PRs's build of dApp are done in `develop` mode
- artifacts are exported as `.tar.gz` compressed files

## Tasks
- [ ]

### PR DESCRIPTION
**Pull request by andrevmatos**
Fixes #1746 , #1749 and #1511 

**Short description**
Provides a service to serve PR builds locally.

To test:
Create a `.env` file on the `serve_pr` folder, containing `CIRCLE_TOKEN=<your_token>`.

Also, create a `serve_pr/app` folder and be sure it has write and execution permissions for user:group `nobody`, as nginx's process will try to run script and write to this folder as such.

Then, after running `docker-compose up`, one should be able to go to https://localhost:8080/?branch=pull/1754 or any other PR/branch and get it downloaded and served on https://localhost:8080/pull/1754 . Notice the branch used on the first request needs to be the upstream branch: for PRs opened from external repo, it'll be `pull/<#PR>`; for PRs opened from some upstream branch, it'll be the actual branch.
To "refresh" the served files (e.g. after a new successful build), access the first (root+param) URL again.

One can also use the script directly, like:
```sh
./ci_dapp.sh branch=pull/1754 -s
```
The `-s` param will cause the build to be served on https://localhost:8080/ with a `python -m http.server`.

A README was added as per @kelsos request.

**Definition of Done**

- [x] Steps to manually test the change have been documented
- [x] Acceptance criteria are met
- [x] Change has been manually tested by the reviewer (dApp) 

**Steps to manually test the change (dApp)**

1.
2.

### CODE REVIEW

**Comment by kelsos** [comment]
Is anything special needed in regard to the personal token to make it work?

For some reason I am getting no response from the API
```
curl -H Circle-Token:*** 'https://circleci.com/api/v2/project/github/raiden-network/light-client/pipeline?branch=pull/1754'
{
  "next_page_token" : null,
  "items" : [ ]
}%        
```

**Comment by kelsos** [comment]
ok basically pull/1754 won't work since it is on the upstream repo and not on  a fork

**Comment by kelsos** [comment]
Also it seems that when running `docker-compose up` the `ci_dapp.sh` copied to the app folder is empty.

**Comment by kelsos** [comment]
I tried quite a few times but things don't seem to work properly for me. Out of all the tries fetching worked once, most of the time it fails with `Script error: closed`. I have no idea why, in some cases, the proper folder is generated in the app folder but other than that nothing seems to happen.

In the one case where it finally worked, I could see no redirect to root. Could you describe how to replicate the redirect step by step? or provide a video of it happening if that is easier?

**Comment by andrevmatos** [comment]
> Is anything special needed in regard to the personal token to make it work?
> 
> For some reason I am getting no response from the API
> 
> ```
> curl -H Circle-Token:*** 'https://circleci.com/api/v2/project/github/raiden-network/light-client/pipeline?branch=pull/1754'
> {
>   "next_page_token" : null,
>   "items" : [ ]
> }%        
> ```

This doesn't work because there's no such branch `pull/1754` (it was just an example). Usually, there is when you PR from an external repo. As one of the paragraphs I wrote on the PR, this branch name is for PRs from outer branches, while on own branches (as is the case with my PR), the branch name is the actual source one.


> Also it seems that when running `docker-compose up` the `ci_dapp.sh` copied to the app folder is empty.

No, it's not. If you look into the `app` folder from the host, you'll see an empty file holding the place for the mounted file on the container, but if you look into the container, you'll see the full script mounted there.

> Out of all the tries fetching worked once, most of the time it fails with `Script error: closed`.

This is a script error. Could be permissions or no artifact on given branch/PR. You can check the last script logs by running in parallel with the running compose (another terminal, same folder) something like: `docker-compose exec dapp cat /tmp/log.txt`

**Comment by andrevmatos** [comment]
> In the one case where it finally worked, I could see no redirect to root. Could you describe how to replicate the redirect step by step? or provide a video of it happening if that is easier?

I fixed the redirect thing already on this PR, by moving router to `hash` mode when on development. Hash mode doesn't meddle with root as history mode, and works fine for relatively served dapp, and it actually doesn't look bad IMO.

**Comment by kelsos** [comment]
I am gonna approve the PR but I have a last request. Can we also add a basic readme
It would be nice to have:
- A small description of the steps you need to take (e.g. .env creation/ folder creation and permissions)
- Linking to the documentation about getting the CIRCLE_TOKEN

**Pull request merged**
