### PR TITLE
Truncates Account screen address on mobile

### PR DESCRIPTION
**Pull request by taleldayekh**
**Thank you for submitting this pull request :)**

Fixes # 

**Short description**
Truncates Account screen address on mobile. I spent some time trying to find a way to change the prop via the CSS but could not. This was the most straight forward solution I could come up with.

**Definition of Done**

- [x] Steps to manually test the change have been documented
- [x] Acceptance criteria are met
- [ ] Change has been manually tested by the reviewer (dApp) 

**Steps to manually test the change (dApp)**

1. Connect to the dApp and pop open the Account screen.
2. Reduce browser window to mobile size and the full address should truncate.

### CODE REVIEW

**Comment by nephix** [comment]
Screenshot 2020-05-19 at 12 43 09

Here's how it currently looks for me with iphone X settings

**Comment by taleldayekh** [comment]
> Here's how it currently looks for me with iphone X settings

Faaaaail, I will fix it. :)

**Comment by taleldayekh** [comment]
Need to add the change log as well. Thank you GitHub actions.

**Comment by nephix** [comment]
Looks good thank you 🙏

**Pull request merged**
