### PR TITLE
Changed wording from "Payment" to "Transfer"

### PR DESCRIPTION
**Pull request by taleldayekh**

### CODE REVIEW

**Comment by christianbrb** [comment]
@taleldayekh Thanks : ) There is an additional [readme ](https://github.com/raiden-network/light-client/blob/c6ce81305e790331606715eddd72a0f55d675168/raiden-ts/README.md)to change.

See: https://github.com/raiden-network/light-client/search?q=payments&unscoped_q=payment 
(I have been also searching for pay, pays and payments)

**Comment by christianbrb** [comment]
There are also some old commits in the PR

**Comment by taleldayekh** [comment]
Changed the text on the image.

**Comment by taleldayekh** [comment]
Just ignore the old commits, I guess I should have made a new branch instead of doing changes on the old one. :)

**Pull request merged**
