### PR TITLE
Transparent overlay instead of blurred in Firefox

### LINKED ISSUE #1781: Pop-up modal its background not blurry in Firefox
## Steps to Reproduce
1. Open dApp in Firefox web-browser
2. Do an action like mint SVT/tokens, a transfer, .. to get a pop-up modal

## Expected Result
- blurry background as for example in Chromium

## Actual Result
- clear background with all details

## Additional Infos (Optional) 
```
- Browser & version: Mozilla Firefox 77.0.1
```

### PR DESCRIPTION
**Pull request by taleldayekh**
Fixes #1781 

**Short description**
Since there is no good workaround for replacing ```backdrop-filter``` and since it is expected for Firefox to eventually enable ```backdrop-filter``` by default, we are going with a temporary solution where the overlay is slightly transparent in Firefox as opposed to blurry.
Screenshot 2020-06-29 at 15 28 31

**Definition of Done**

- [x] Steps to manually test the change have been documented
- [x] Acceptance criteria are met
- [ ] Change has been manually tested by the reviewer (dApp) 

**Steps to manually test the change (dApp)**

1. Connect to the dApp and open any dialog.

### CODE REVIEW

**Comment by taleldayekh** [comment]
Also, I could not find the dialog where there was an issue clicking outside to close.

**Comment by christianbrb** [comment]
@taleldayekh 
Screenshot looks nice :) Is it changed at all places? I was under the impression, that the implementation at different places has been different: at least from looking at the dApp.

**Comment by taleldayekh** [comment]
@christianbrb 
It is changed in all places. We only use one blurred overlay component.

**Comment by taleldayekh** [comment]
@weilbith Yes, it simply looked better with a dark transparent background.

**Pull request merged**
