### PR TITLE
sdk: add disclaimer to the README

### PR DESCRIPTION
**Pull request by weilbith**
Part of #1658

I don't know how to format best within Markdown. Open for suggestions.

### CODE REVIEW

**Comment by taleldayekh** [comment]
> I don't know how to format best within Markdown. Open for suggestions.

Maybe put it in blockquotes would be nice?
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#blockquotes

**Comment by weilbith** [comment]
@taleldayekh how do you think [this looks](https://github.com/weilbith/light-client/tree/feature/sdk-add-disclaimer/raiden-ts)?

**Comment by taleldayekh** [comment]
> @taleldayekh how do you think [this looks](https://github.com/weilbith/light-client/tree/feature/sdk-add-disclaimer/raiden-ts)?

All good! 👍

**Comment by weilbith** [comment]
Okay then I clean up this branch and close the PR. :+1:

**Pull request merged**
