### PR TITLE
0.11.0 -> v0.11.1

### PR DESCRIPTION
**Pull request by weilbith**
Part of #1951

This is about a tiny path release which is mainly just for the update of the contracts to `v.37.1` to be compatible with the Python client `v1.1.1`.

### CODE REVIEW

**Comment by weilbith** [comment]
I'm confused why the tests do fail. This PR does not include any code changes.

**Comment by andrevmatos** [comment]
Please, bump also raiden-cli, and change the script to bump it together with the other packages. The failure may be some small flatness, and should go away on a new run

**Comment by weilbith** [comment]
As asked, I rebased on `master` to include Talel his fix. I also extended the prepare release script to include the CLI bumping. The CLI also now got its first version of a CHANGELOG file.

**Comment by weilbith** [comment]
Okay this is pretty bad that the test are flaky. Anyways it should be fine I guess. Starting to prepare the GitHub release text now.

**Pull request merged**
