### PR TITLE
Chore/implement custom license checker

### PR DESCRIPTION
**Pull request by weilbith**
Please read 3f77156c403cb539ba0bc5b4b0a59138612b35f8

### CODE REVIEW

**Comment by weilbith** [comment]
Alright. I had to push that many fixup commits, because I can't fully test this action locally. And the issues actually occurred especially in the GitHub environment. Now it is working as expected. Therefore I will squash the commits. Finally we can adapt the list of allowed licenses.

**Comment by weilbith** [comment]
I'll now focus on some code improvements. Probably also convert it to use TypeScript.

**Comment by weilbith** [comment]
Alright, I gave up. Its too much effort for the moment to make it work differently than GitHub expects it. Therefore the actions implementation must be packages and committed. We did already followed this "recommended" approach for the other action we have. We might want to revisit this at some point in time.

**Comment by weilbith** [comment]
As I added all allowed licenses in the last commit, all checks succeed now. You can see a failing run [here](https://github.com/raiden-network/light-client/pull/2830/checks?check_run_id=2893481735) where I did not include all licenses on purpose.

gscreenshot_2021-06-23-113843

**Comment by weilbith** [comment]
Sorry I missed to lint the code for the last changes. Therefore I had to fix it (though not covered in CI). 

The CodeClimate complains got also accepted as they target the ****** `./dist/` folder only.

**Review by palango — APPROVED** [review]
🤖

**Pull request merged**
