### PR TITLE
Bugfix/dapp fix routing issues

### LINKED ISSUE #2159: Account screen routing not working when disconnected
## Steps to Reproduce
1. Disconnect the dApp.
2. Click on the gray identicon to access the account screen.

## Expected Result
- The account screen to be accessible with a limited set of menu items.

## Actual Result
- Cannot access the account screen because the routing is blocking it.

### PR DESCRIPTION
**Pull request by weilbith**
**Thank you for submitting this pull request :)**

Fixes #2159

**Short description**

Main code changes are for tests...

**Definition of Done**

- [ ] Steps to manually test the change have been documented
- [ ] Acceptance criteria are met
- [ ] Change has been manually tested by the reviewer (dApp) 

**Steps to manually test the change (dApp)**

1.1 Do not connect (eventually accept disclaimer) and try to access account route

1.2 Try to do a transfer from the transfer routes inputs

### CODE REVIEW

**Review by taleldayekh — APPROVED** [review]
I served the PR and tried accessing the account screen as well as making a transfer and it works like a charm. Thanks for fixing it so fast.

**Comment by weilbith** [comment]
@taleldayekh any idea why the code coverage dropped? :scream:

**Comment by taleldayekh** [comment]
> @taleldayekh any idea why the code coverage dropped? 😱

No idea, same for my but I think it's only the SDK part that dropped the Coverage.

**Comment by weilbith** [comment]
Okay the only file that dropped in coverage and was actually touched by me was the connection guard. And the 9 lines not executed is the constant array of the account routes. Therefore I'll merge it with the given review.

**Pull request merged**
