### PR TITLE
Bugfix/dapp vue router account warning

### LINKED ISSUE #2142: Vue-Router account child route warning message
## Steps to Reproduce
1. Visit the light client dApp (any mode)
2. Open the browser console

## Expected Result
- No errors/warnings from 1st party

## Actual Result
- Warning by `vue-router`

```
 [vue-router] Named Route 'account' has a default child route. When navigating to this named route (:to="{name: 'account'"), the default child route will not be rendered. Remove the name from this route and use the name of the default child route for named links instead.
```

### PR DESCRIPTION
**Pull request by weilbith**
**Thank you for submitting this pull request :)**

Fixes #2142 

**Short description**
Nothing to add.
Based on #2134 Will become rebased as soon as the parent PR gets merged. Just review the last commit please.

**Definition of Done**

- [ ] Steps to manually test the change have been documented
- [ ] Acceptance criteria are met
- [ ] Change has been manually tested by the reviewer (dApp) 

**Steps to manually test the change (dApp)**

1. Start the dApp
2. Check the console output to see no warning anymore

### CODE REVIEW

**Comment by weilbith** [comment]
Damn it, I'm stupid. Maybe too late... I'm not running the tests locally because I though it is trivial. But the account route has child routes which need some special treatment within the tests. I'll add this in a seconds.

**Review by taleldayekh — APPROVED** [review]
We went through all code changes together and all good! Great job with all the refactoring! 👍

**Comment by weilbith** [comment]
I do a rebase on `master` now. As result only the last commit should remain.

**Comment by weilbith** [comment]
There is no need to add a CHANGELOG entry here.

**Pull request merged**
