### PR TITLE
Feature/dapp notification snackbar is clickable

### LINKED ISSUE #2458: Notification window is not centered and clicking on it does not open the notification panel
## Steps to Reproduce
1. Access https://lightclient.raiden.network/staging/
2. Connect

## Expected Result
- The notification "Backup your state" is centered
- If you click on the notification the notification window opens

## Actual Result
- It is not centered
- It cannot be clicked

grafik

## Additional Infos (Optional) 
```
- Browser & version
- Browser console errors
- Device / OS
```

### PR DESCRIPTION
**Pull request by weilbith**
Fixes #2458

**Short description**
This does (so far) not handle the request to make the snackbar centered. This still needs clarification by the issuer @christianbrb 
The most time/work of this PR was invested into refactoring the unit tests (as we agreed to do this when ever we stumble over it) and make the component properly testable (e.g. see conditional rendering in addition to Vuetifies snackbar model variable).

**Definition of Done**

- [x] Steps to manually test the change have been documented
- [ ] Acceptance criteria are met
- [ ] Change has been manually tested by the reviewer (dApp) 

**Steps to manually test the change (dApp)**

1. Trigger a notification (e.g. simply use the backup notification if you haven't used the dApp this day already)
2. Click on the snackbar (everything just not the close button)
3. Verify that the notification panel has opened
4. Verify that the snackbar itself got hidden immeditately

### CODE REVIEW

**Review by taleldayekh — APPROVED** [review]
Great and thank you! ❤️

**Comment by weilbith** [comment]
Note from the issue: Christian mixed horizontal and vertical. So this requirement is already satisfied.

**Comment by weilbith** [comment]
I'm going to rebase that now to resolve the merge conflicts.

**Comment by agatsoh** [comment]
@weilbith 
I am testing this on my local and i get this error here on the console. Also I dont get the usual 
`Back up state ` snackbar on each startup.

snackbar_error

**Comment by weilbith** [comment]
> @weilbith
I am testing this on my local and i get this error here on the console. 

This error is expected. The Vue router is a little bit stupid here. It isn't breaking anything. I hope with Vue 3 this is solved better. Because the only way to fix this is super ugly atm.

> Also I dont get the usual Back up state snackbar on each startup.

You should only get this all 24h anyways. What does not working here for you?f

**Comment by agatsoh** [comment]
Ok disregard my earlier comment I tested this on a node which does not have service tokens and i clicked the 
`Receiving Transfers is disabled` and it opened the notification panel.
So looks good.
@weilbith

**Review by agatsoh — APPROVED** [review]
looks good to me.

**Pull request merged**
