### PR TITLE
dapp: add check for required browser features

### LINKED ISSUE #2497: dApp - disable if browser does not support required features
## Description

The dApp is based on some modern features of web-browsers like service workers. To keep the implementation simple without the need to maintain a lot of backwards compatible code or messages, we just "disable" the applications in such browsers. This should like we already detect if JavaScript is enabled/available and if not do not even start to render/mount the application.
This also keeps legal requirements issues simple as we only have a single "version" of the application that fully aligns with all requirements no matter what.

## Acceptance criteria
- a list of features we require
- extended check for required features outside of Vue 

## Tasks
- [ ]

### PR DESCRIPTION
**Pull request by weilbith**
Fixes #2497 

**Short description**
Please try it yourself in your web-browser an make sure that the application gets served for you.

**Definition of Done**

- [x] Steps to manually test the change have been documented
- [x] Acceptance criteria are met
- [ ] Change has been manually tested by the reviewer (dApp) 

**Steps to manually test the change (dApp)**

1. Run the dApp
2. Make sure you get not shown the error message.

### CODE REVIEW

**Comment by palango** [comment]
Looks good on the first view, but you should add a changelog entry.

And do you know of any browser that doesn't support the feature set to test the bad case?

**Comment by weilbith** [comment]
> Looks good on the first view, but you should add a changelog entry.

Good idea. I'll do so!

**Comment by weilbith** [comment]
> And do you know of any browser that doesn't support the feature set to test the bad case?

Hmm. Maybe an old Internet Explorer which stopped development some years ago.
@christianbrb as the only Windows user in the team: could you try install the old IE?

**Comment by weilbith** [comment]
@palango I got an old Firefox v41.0 from an achieve. This works. Means I get the message and not the application.
Unfortunately this fu**** up my actual Firefox setup (the config files, plugins, user data,,,). I'll need some time to fix it.

@christianbrb forget about my comment. I did it already.  --^

**Comment by palango** [comment]
> @palango I got an old Firefox v41.0 from an achieve. This works. Means I get the message and not the application.
> Unfortunately this fu**** up my actual Firefox setup (the config files, plugins, user data,,,). I'll need some time to fix it.

Oh damn, sorry for that! But thanks for testing.

**Review by palango — APPROVED** [review]

**Comment by weilbith** [comment]
I'll rebase to resolve the merge conflicts.

**Pull request merged**
