### PR TITLE
deploy: Run staging/development on development env

### PR DESCRIPTION
**Pull request by palango**
**Short description**

Run staging on the development environment.

The development environment is closer to the mainnet environment with the updates synapse servers. This change run staging and local development build on the development environment.

**Definition of Done**

- [ ] Steps to manually test the change have been documented
- [ ] Acceptance criteria are met
- [ ] Change has been manually tested by the reviewer (dApp) 

**Steps to manually test the change (dApp)**

1.
2.

### CODE REVIEW

**Review by andrevmatos — APPROVED** [review]
lgtm; it's also needed to update the `hub.raiden.eth` node to match

**Comment by palango** [comment]
> lgtm; it's also needed to update the `hub.raiden.eth` node to match

How do I update that one?

**Comment by andrevmatos** [comment]
> How do I update that one?

https://github.com/raiden-network/light-client/blob/master/UPGRADE-TESTENV.md#raiden-hub

**Comment by palango** [comment]
Mh, I guess we cannot update the hub like this as the demos might rely on it. Do we really need it for staging?

**Comment by andrevmatos** [comment]
Maybe not, once #211 is finished, the dApp (on either environments) won't have hub hardcoded anymore, so it'd be ok to leave it behind on the demo001 environment. But then we shouldn't merge this until we took care of the hardcoded hub there.

**Pull request merged**
