### PR TITLE
Bugfix/dapp too many connected tokens lead to ui overflow

### LINKED ISSUE #2138: Opening multiple channels with different tokens breaks token select overlay
## Steps to Reproduce
1. Open multiple channels.
2. Navigate to token select.

## Expected Result
- To have a list of connected tokens which is scrollable and does not break the layout.

## Actual Result
Screenshot 2020-09-15 at 17 19 34

### PR DESCRIPTION
**Pull request by weilbith**
**Thank you for submitting this pull request :)**

Fixes #2138

**Short description**
This was solved by exporting the token list part of the select token view into its own component and re-use it also for the broken token overlay. Therefore this PR includes new components, adopted components, new tests, adopted tests, and some optimizations of former styling and templating.

**Definition of Done**

- [ ] Steps to manually test the change have been documented
- [ ] Acceptance criteria are met
- [ ] Change has been manually tested by the reviewer (dApp) 

**Steps to manually test the change (dApp)**

1. Run the client with an account that has many open channels in different token networks
2. Click on switch token
3. Make sure there is a scrollable list of connected tokens and no overflow in the UI

### CODE REVIEW

**Review by taleldayekh — CHANGES_REQUESTED** [review]
I'm serving and testing your PR in Chrome and I'm experiencing some issues.

The list is still overflowing.

Screenshot 2020-09-29 at 11 01 17

When there is only one token it appears in the middle, could you please adjust so it is on top of the list?

Screenshot 2020-09-29 at 11 02 45

Also, I'm getting a bunch of console errors when I access the token list from `Connect new token`.

Screenshot 2020-09-29 at 11 04 18

**Comment by weilbith** [comment]
@taleldayekh thanks for the good test! Sorry that this is not working properly :expressionless:

**Comment by weilbith** [comment]
I fixed all three issue and tested them locally also with Chromium.
@taleldayekh Could you please give it another try?

**Review by taleldayekh — APPROVED** [review]
Your changes works like a charm, good job! Go ahead and merge.

**Comment by weilbith** [comment]
Okay, then I'll rebase the fixup commits and merge as soon as CI is through again.

**Pull request merged**
