### PR TITLE
Bugfix/dapp connect screen displays transfer screen title

### LINKED ISSUE #2096: dApp displays "Transfer" header on connect screen
## Steps to Reproduce
1. Make sure the disclaimer is not hidden. Accept the disclaimer and proceed to the transfer screen.
2. Reload browser window and accept disclaimer again and stay at the connect screen.

## Expected Result
- The header to display nothing, if the dApp is not connected

## Actual Result
- Header displays `Transfer`

I suspect something is broken because the connect screen is not necessarily always the first screen since the disclaimer was introduced. As can be seen in the URL that has the transfer screen route in it.

## Additional Infos (Optional) 
Screenshot 2020-08-19 at 13 46 02

### PR DESCRIPTION
**Pull request by weilbith**
Fixes #2096

**Short description**
This root of this issue was a much bigger mess in design than expected. The changes include a ton of moved and removed code. The actual changes and the final fix are not too big. Also the commit messages should be descriptive enough to tell what happened, it would be pretty cumbersome to review it plainly. Therefore I recommend that @taleldayekh and I have a meeting to go over this PR changes together. This should speed up the process and keeps the reviewer (a.k.a. Talel) happy on his first day of work after holidays. :laughing: 

**Definition of Done**

- [ ] Steps to manually test the change have been documented
- [ ] Acceptance criteria are met
- [ ] Change has been manually tested by the reviewer (dApp) 

**Steps to manually test the change (dApp)**

1.
2.

### CODE REVIEW

**Review by taleldayekh — APPROVED** [review]
Thanks for the walkthrough of the code changes and for taking the time to clean up and improve the routing design. Very nice job, go ahead and merge. 👍

**Comment by weilbith** [comment]
I'm rebasing on `master` now to get the fixed dependencies that make the CI working again.

**Comment by weilbith** [comment]
This has become quite messy. The refactorings caused testing issues. These then lead to further smaller refactorings. Sorry for that. I should have stopped earlier and continue in future PRs. I'll clean up the branch now.

**Review by taleldayekh — APPROVED** [review]
We went through all code changes together and all good! Great job with all the refactoring! 👍

**Comment by weilbith** [comment]
I'll do a final rebase on `master` to squash the fixup commits and resolve eventual upcoming conflicts due to Talel his just merged PR.

**Pull request merged**
