### PR TITLE
Mobile app setup

### LINKED ISSUE #2796: dApp: merge mobile app setup branch into master
## Description

First merge `master` into the `mobile-app-setup` and then open a PR from there to `master` to get the verification by CI. Eventually a rebase will work better if there are too many too complicated conflicts. It is also necessary to remove the hard-coded private key and RPC-URL from the mobile branch. Also the browser extension should be disabled.

### PR DESCRIPTION
**Pull request by weilbith**
**Thank you for submitting this pull request :)**

Fixes #2796

**Short description**
The requested additional changes are within the commits after the merge-commit.

### CODE REVIEW

**Comment by weilbith** [comment]
In draft mode because we still need a final verification of the whole release tool-chain with an internal test release for Maria. This task is currently stuck due to secret issues and local PC setups.
Anyway I opened this PR to get the CI feedback already.

**Comment by weilbith** [comment]
I have to merge `master` in again as there where apparently some version updates by the dependabot since my last merge.

**Comment by weilbith** [comment]
Please note that only the commits after the first merge from `master` are relevant (from b2c569880ffcb33dc86cf63a85f64fd14ea5ec75). Everything before got merged into the mobile branch via PRs and thereby was reviewed already.

**Review by palango — APPROVED** [review]

**Comment by weilbith** [comment]
Waiting for Maria to confirm that she install the app herself.

**Comment by weilbith** [comment]
Jannik was so kind to test it out on his phone. Works. ✔️ 
He was very critical about some punctuation in the disclaimer 😆

**Pull request merged**
