### PR TITLE
Mainnet Release v2.1.0 Kṛttikā

### PR DESCRIPTION
**Pull request by weilbith**
# 🧱  New Raiden Light Client SDK, dApp and CLI

> **INFO:** The Light Client SDK, CLI and dApp are all **work in progress** projects. All three projects have been released for **mainnet** and all code is available in the Light Client repository. As this release still has its limitations and is a **beta** release, it is crucial to read this readme including the security notes carefully before using the software.

This new version adds a feature to the dApp that protects the user from loading temporary updates unintentionally. Besides the side effect of loading a different version temporary it is important that users always confirm updates and manually trigger the installation of a new version. Unintended updates can for example happen on a force-reload of of the web-browser. For more information, refer to the notes from the [v2.0.0 release](https://github.com/raiden-network/light-client/releases/tag/v2.0.0).

Raiden dApp
-------------------------------
### Added

- [#3024] Prevent the usage of uninstalled versions

### CODE REVIEW

**Review by andrevmatos — APPROVED** [review]
lgtm!

**Comment by weilbith** [comment]
@andrevmatos feel free to edit the test how ever you like.

**Comment by weilbith** [comment]
We need to rebase once #3028 got merged. The end-to-end tests should then run also with the bumped version here.

**Review by andrevmatos — APPROVED** [review]

**Comment by weilbith** [comment]
For the protocol: the end-to-end tests work locally. We suffer from some flakyness here that is not related to our changes. Andres can explain it better.

**Comment by weilbith** [comment]
Workflow succeeded! CircleCI hangs due to some parallel and canceled jobs.

**Pull request merged**
