### PR TITLE
Feature/dapp split store for new udc module

### PR DESCRIPTION
**Pull request by weilbith**
**Thank you for submitting this pull request :)**

Preparation for #2308 which became too big by itself.

**Short description**
While the last commit is the by far biggest one, the first two commits are the interesting ones. Please read their messages for more information. The last commit is just about tests, including a lot of refactoring into the direction of our test guide agreement.

@taleldayekh could you please run the end-to-end tests locally? My setup does not work anymore due to mismatching iptable versions etc. I'll need to fix that any time soon.

PS: There might be something awkward in the commits, since I forgot the correct linting and tried to fix it afterwards and merge into the "old" commits. Not the best approach and I could have it done better...

**Definition of Done**

- [ ] Steps to manually test the change have been documented
- [ ] Acceptance criteria are met
- [ ] Change has been manually tested by the reviewer (dApp) 

**Steps to manually test the change (dApp)**

1.
2.

### CODE REVIEW

**Comment by weilbith** [comment]
There is no need to extend the changelog yet.

**Review by taleldayekh — APPROVED** [review]
Finally someone took care of those async getters, remember that we talked about them a couple of months ago already. 😃 Also nice work with starting refactoring the store, makes total sense to split it up. Well done!

**Comment by weilbith** [comment]
Unfortunately the dApp their end-to-end test do fail locally. We analyzed the issue in the developer chat with Andre. It seems to be unrelated to this PR. But we need to have them passing through to make sure I did not messed up something. While the many tests have passed until the error occurs I'm positive this PR is fine. But we need to be sure.
Therefore I'll temporally enable the nightlies here to get the verification. When I squash the fixup commits I'll also remove the nightlies again.

**Comment by weilbith** [comment]
Alright, the tests are working fine. So I'll make this PR ready to get merged.

**Comment by weilbith** [comment]
As I said there is no need for a changelog entry since this were only internal code changes to make future planned features easier to develop. Therefore I merge this now.

**Pull request merged**
