### PR TITLE
Feature/dapp redesign udc screen

### LINKED ISSUE #2220: I want to know, that I have to withdraw the tokens from the UDC on the UDC screen
## User Story
As Chris I want to know, that I have to withdraw the tokens from the UDC on the UDC screen so that I am not getting confused.

## Acceptance criteria
- It should follow the design
- The information area on the top is not getting implemented
- We use the already existing color-variables (incl. new account screen button colors)
- No text is smaller than 12px
- User Contract Deposit Balance instead of USER CONTRACT DEPOSIT BALANCE
- Without the area "Withdrawals in progress" -> Issue #2308 

## Tasks
- [x] Meeting with @sashseurat 
- [x] Design @sashseurat 

## Design
[The click-dummy](https://www.figma.com/proto/5H8EOoC2SntoXZuTtUZsyY/LC-UDC-Screen-Optimisation?node-id=14%3A27&viewport=-1799%2C1629%2C1&scaling=min-zoom)

LC - No Planned Withdrawals

### PR DESCRIPTION
**Pull request by weilbith**
**Thank you for submitting this pull request :)**

Fixes #2220

**Short description**
- This is basically just design. It includes some other "fixes".
- Based on #2369 therefore just a draft pull request.
- I enabled the nightlies temporally since I still have issues with the e2e tests locally

**Definition of Done**

- [X] Acceptance criteria are met

### CODE REVIEW

**Comment by weilbith** [comment]
The git check for the CHANGELOG is broken. I actually added an entry.

**Comment by weilbith** [comment]
Since the parent PR got merged. I'm now rebasing and resolving the conflicts.

**Comment by weilbith** [comment]
@taleldayekh could you give this a review now? Then I can start to work faster on the other two missing issues.

**Review by taleldayekh — APPROVED** [review]
Wunderschön ❤️

**Pull request merged**
